name: Resume Chatbot CI

on:
  push:
    paths:
      - "images/streamlit/**"
      - ".github/workflows/streamlit.yml"
  pull_request:
    paths:
      - "images/streamlit/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        working-directory: images/streamlit
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check Streamlit app compiles
        working-directory: images/streamlit
        run: |
          python -m py_compile src/resume_chatbot/streamlit_app.py
