name: Run Resume Chatbot Tests

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r images/streamlit/requirements.txt
          pip install pytest

      - name: Run Pytest
        env:
          PYTHONPATH: ${{ github.workspace }}/images/streamlit/src
        run: |
          pytest tests/unit
